version: '3.8'

services:

 app_db:
  image: postgres
  container_name: app_db
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: passwd
    POSTGRES_DB: app_db
  ports:
    - "5432:5432"
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U user -d app_db" ]
    interval: 8s
    timeout: 4s
    retries: 4